apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: ns1
spec:
  containers:
    - name: my-container
      image: nginx:latest

---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: ns1
spec:
  containers:
    - name: my-container
      image: nginx:latest

---
apiVersion: v1
kind: Pod
metadata:
  name: pod3
  namespace: ns2
spec:
  containers:
    - name: my-container
      image: nginx:latest

---
apiVersion: v1
kind: Pod
metadata:
  name: pod4
  namespace: ns2
spec:
  containers:
    - name: my-container
      image: nginx:latest